version: '3.9'

services:
  db:
    image: ankane/pgvector
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: /entrypoint.sh
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434

  frontend:
    build:
      context: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - web

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8g

  ollama-init:
    image: curlimages/curl
    depends_on:
      - ollama
    entrypoint: >
      sh -c "sleep 5 &&
            curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3\"}'"


volumes:
  pgdata:
  static_volume:
  media_volume:
  ollama_models:
