version: '3.9'

services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn reqcheck.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

volumes:
  pgdata:
  static_volume:
