version: '3.9'

services:
  db:
    image: ankane/pgvector
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: /entrypoint.sh
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
