# Generated by Django 5.2.1 on 2025-06-12 01:33

import business_visions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="documents_pdf", validators=[business_visions.models.validate_pdf]
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        to="projects.Project",
                        on_delete=models.CASCADE,
                        related_name="business_visions",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
