# Generated by Django 5.2.1 on 2025-06-16 19:40

import business_visions.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("business_visions", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
                ("chunk_text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="documents_pdf", validators=[business_visions.models.validate_pdf]
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_visions",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
