# Generated by Django 5.2.1 on 2025-06-16 02:22

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_visions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
                ("chunk_text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
