# Generated by Django 5.2.1 on 2025-08-10 15:10

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_visions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfchunk",
            name="business_vision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="business_visions.businessvision",
            ),
        ),
        migrations.AlterField(
            model_name="pdfchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
