# Generated by Django 5.2.1 on 2025-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requirements", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        to="projects.Project",  # ou 'appname.Project'
                        on_delete=models.CASCADE,
                        related_name="requirements",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
